- name: Deploy Application in OpenShift 4
  hosts: all
  become: yes
  become_user: root
  tasks:
    #- name: Configure and Point to KUBECONFIG file
    #  command: "export KUBECONFIG='/home/mmanjrek-redhat.com/ocp/auth/kubeconfig'"         
    - name: Set Tower project
      command: "oc project tower"
      
    - name: Deploy Application
      command: "oc new-app https://github.com/openshift/ruby-hello-world.git#beta4"
    
    - name: Expose Service
      command: "oc expose svc/ruby-hello-world"
